name: Build Mod

# Говорим, когда запускать сборку
on:
  push:             # При каждом пуше в любую ветку
  workflow_dispatch: # Чтобы можно было запустить вручную из интерфейса GitHub

jobs:
  build:
    runs-on: ubuntu-latest # Используем сервер с Linux

    steps:
      # 1. Забираем код из репозитория
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Java 21 (твоя версия)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Даем права на выполнение скрипта Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Запускаем саму сборку!
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Сохраняем полученный .jar файл как артефакт, чтобы его можно было скачать
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-artifacts
          path: build/libs/*.jar